---
# Items that apply to ALL profiles:
eureka:
  instance:
    preferIpAddress: true
    ip-address: 192.168.99.100  
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8010/eureka/,http://192.168.99.100:8011/eureka/,http://192.168.99.100:8012/eureka/,http://192.168.99.100:8013/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

